{% set name = "cogeo-mosaic" %}
{% set version = "8.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cogeo_mosaic-{{ version }}.tar.gz
  sha256: bf6c67360873ba3cac8938e8df66c72c96ba3831174883a84b85344c6a91eb58

build:
  number: 0
  noarch: python
  entry_points:
    - cogeo-mosaic = cogeo_mosaic.scripts.cli:cogeo_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - hatch-fancy-pypi-readme
    - python {{ python_min }}
  run:
    - attrs
    - morecantile >=5.0,<7.0
    - shapely >=2.0,<3.0
    - numpy
    - pydantic
    - pydantic-settings
    - python >={{ python_min }}
    - httpx
    - rasterio
    - rio-tiler >=7.0,<8.0
    - supermorecado
    - cachetools
    - boto3
    - google-cloud-storage
    - cligj
    - click
    - click-plugins

test:
  imports:
    - cogeo_mosaic
    - cogeo_mosaic.backends
    - cogeo_mosaic.scripts.cli
  commands:
    - pip check
    - cogeo-mosaic --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://developmentseed.org/cogeo-mosaic
  summary: Create mosaicJSON.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/developmentseed/cogeo-mosaic.git

extra:
  recipe-maintainers:
    - andrewannex
    - lsetiawan
    - andrewannex
