{% set name = "cogeo-mosaic" %}
{% set version = "5.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a981a1cd589db9e6c81fd5a5e75b82360e854c52e98d96abfa9db846cc295d9b

build:
  number: 0
  noarch: python
  entry_points:
    - cogeo-mosaic = cogeo_mosaic.scripts.cli:cogeo_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.9
  run:
    - attrs
    - cachetools
    - httpx
    - morecantile >=3.1,<4.0
    - pydantic
    - pygeos >=0.10
    - python >=3.7,<3.9
    - rasterio
    - rio-tiler >=3.1,<4.0
    - supermercado
    - boto3
    - google-cloud-storage

test:
  imports:
    - cogeo_mosaic
    - cogeo_mosaic.backends
    - cogeo_mosaic.scripts.cli
  commands:
    - pip check
    - cogeo-mosaic --help
  requires:
    - pip

about:
  home: https://developmentseed.org/cogeo-mosaic
  summary: Create mosaicJSON.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/developmentseed/cogeo-mosaic.git

extra:
  recipe-maintainers:
    - lsetiawan
