{% set name = "cogeo-mosaic" %}
{% set version = "5.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cogeo-mosaic-{{ version }}.tar.gz
  sha256: 8ff100ecc3a96fcc019edc2c0675469474b3dd43a3bf39267772f265481e1f8f

build:
  number: 0
  noarch: python
  entry_points:
    - cogeo-mosaic = cogeo_mosaic.scripts.cli:cogeo_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-fancy-pypi-readme >=22.5.0
    - pip
  run:
    - python >=3.8
    - attrs
    - morecantile >=3.1,<4.0
    - shapely >=2.0b2,<3.0
    - pydantic
    - httpx
    - rasterio
    - rio-tiler >=3.1.0,<5.0
    - cachetools
    - supermercado

test:
  imports:
    - cogeo_mosaic
    - cogeo_mosaic.backends
    - cogeo_mosaic.scripts.cli
  commands:
    - pip check
    - cogeo-mosaic --help
  requires:
    - pip

about:
  home: https://developmentseed.org/cogeo-mosaic
  summary: Create mosaicJSON.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/developmentseed/cogeo-mosaic.git

extra:
  recipe-maintainers:
    - lsetiawan
